# Generated by Django 3.1.5 on 2021-01-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=1024, null=True)),
                ('latitude', models.DecimalField(decimal_places=16, default=None, max_digits=22, null=True)),
                ('longitude', models.DecimalField(decimal_places=16, default=None, max_digits=22, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.locationdata'),
        ),
    ]
