# Generated by Django 3.1.5 on 2021-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210123_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clothing_preference',
            field=models.CharField(choices=[('M', 'Male presenting clothing'), ('F', 'Female presenting clothing'), ('A', 'Any')], default='A', max_length=1, verbose_name='user preference'),
        ),
        migrations.AddField(
            model_name='user',
            name='pair',
            field=models.CharField(choices=[('L', 'Left foot'), ('R', 'Right foot')], default='l', max_length=1, verbose_name='pair'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.IntegerField(default=7.5, verbose_name='size'),
            preserve_default=False,
        ),
    ]
