# Generated by Django 3.1.5 on 2021-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210123_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='size',
            field=models.FloatField(verbose_name='size'),
        ),
    ]
