# Generated by Django 3.1.6 on 2021-02-12 05:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210212_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
