# Generated by Django 3.1.6 on 2021-02-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_locationdata_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='authentication.locationdata'),
        ),
    ]
