# Generated by Django 3.1.5 on 2021-01-23 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0002_auto_20210123_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claimaint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
