# Generated by Django 3.1.6 on 2021-02-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20210123_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='claimaint',
            new_name='claimant',
        ),
    ]
